# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-13 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('address_title', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('email_title', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=70, null=True)),
                ('title_phone_for_customers', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('phone_for_customers', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('title_phone_for_partners', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('phone_for_partners', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Розділ "Контакти"',
                'verbose_name_plural': 'Розділи "Контакти"',
            },
        ),
    ]
