# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-17 20:22
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='address',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='address_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone_for_customers',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone_for_partners',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='title_phone_for_customers',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='title_phone_for_partners',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
