# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-13 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='ProjectImage',
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'verbose_name': 'Категорія продукту', 'verbose_name_plural': 'Категорії продукту'},
        ),
    ]
