# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-28 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180313_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPageDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Опис сторінки проекти',
                'verbose_name_plural': 'Описи сторінки проекти',
            },
        ),
        migrations.CreateModel(
            name='ProjectPageName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Назва сторінки проекти',
                'verbose_name_plural': 'Назви сторінки проекти',
            },
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'verbose_name': 'Категорія проекту', 'verbose_name_plural': 'Категорії проектів'},
        ),
    ]
