# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-24 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180324_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageprojectsdescription',
            name='sub_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
