# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-12 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_pageprojectsdescription_sub_title'),
        ('projects', '0003_auto_20180328_1157'),
    ]

    operations = [
    ]
