# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-12 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_merge_20180412_1612'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectPageDescription',
        ),
        migrations.DeleteModel(
            name='ProjectPageName',
        ),
    ]
