# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-16 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20180412_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='short_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
