# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-16 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectcategory_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageprojectsdescription',
            name='short_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
