# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-20 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0006_auto_20180620_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='client_name',
            field=models.CharField(default=None, max_length=128, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='phone_number',
            field=models.CharField(default=None, max_length=128, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='text',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Коментар'),
        ),
    ]
