# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-03 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0008_auto_20180620_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
