# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-09 14:31
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0009_auto_20180703_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, verbose_name='Номер телефону'),
        ),
    ]
