# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-25 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_auto_20180517_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='short_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
