# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-01 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180401_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
